/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.51
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The APIResponse model module.
 * @module model/APIResponse
 * @version 1.0.0
 */
export class APIResponse {
  /**
   * Constructs a new <code>APIResponse</code>.
   * @alias module:model/APIResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>APIResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/APIResponse} obj Optional instance to populate.
   * @return {module:model/APIResponse} The populated <code>APIResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new APIResponse();
      if (data.hasOwnProperty('message'))
        obj.message = ApiClient.convertToType(data['message'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} message
 */
APIResponse.prototype.message = undefined;

