/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.51
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The FileDTO model module.
 * @module model/FileDTO
 * @version 1.0.0
 */
export class FileDTO {
  /**
   * Constructs a new <code>FileDTO</code>.
   * @alias module:model/FileDTO
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>FileDTO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FileDTO} obj Optional instance to populate.
   * @return {module:model/FileDTO} The populated <code>FileDTO</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new FileDTO();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('path'))
        obj.path = ApiClient.convertToType(data['path'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('size'))
        obj.size = ApiClient.convertToType(data['size'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {String} name
 */
FileDTO.prototype.name = undefined;

/**
 * @member {String} path
 */
FileDTO.prototype.path = undefined;

/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
FileDTO.TypeEnum = {
  /**
   * value: "FILE"
   * @const
   */
  FILE: "FILE",

  /**
   * value: "FOLDER"
   * @const
   */
  FOLDER: "FOLDER"
};
/**
 * @member {module:model/FileDTO.TypeEnum} type
 */
FileDTO.prototype.type = undefined;

/**
 * @member {Number} size
 */
FileDTO.prototype.size = undefined;

