# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.file_dto import FileDTO  # noqa: E501
from swagger_client.rest import ApiException


class TestFileDTO(unittest.TestCase):
    """FileDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFileDTO(self):
        """Test FileDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.file_dto.FileDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
