# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.controller_api import ControllerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestControllerApi(unittest.TestCase):
    """ControllerApi unit test stubs"""

    def setUp(self):
        self.api = ControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_browse_remote_directory(self):
        """Test case for browse_remote_directory

        """
        pass

    def test_delete_remote_file(self):
        """Test case for delete_remote_file

        """
        pass

    def test_download_remote_file(self):
        """Test case for download_remote_file

        """
        pass

    def test_rename_remote_file(self):
        """Test case for rename_remote_file

        """
        pass

    def test_upload_local_file(self):
        """Test case for upload_local_file

        """
        pass


if __name__ == '__main__':
    unittest.main()
